Map 1795
sparkgeo/storymap-series pull request #5
Opened 2017-07-04 19:10 UTC by phloem7

npm install
npm install –g grunt-cli
grunt

Can test either src or deploy, for example:
http://localhost:8000/src/demo.html?appid=10d52161999d4b65bb464549d8978408
http://localhost:8000/deploy/demo.html?appid=feae8ba75ec14bd5a3ba33586d62b2e1

More appids available at: https://storymaps.arcgis.com/en/app-list/map-series/gallery-series/#s=0&md=storymaps-apps:map-series

2017-07-04 20:56 UTC, aspcanada requested changes

2017-07-04 20:56 UTC, aspcanada commented on src/app/main-config.js
> +            ['maptiks', '//cdn-dev.maptiks.com/esri3/mapWrapper.js']
keep this using prod in the repo, and use circle to deploy the correct version.

2017-07-04 20:56 UTC, aspcanada commented on src/app/storymaps/tpl/core/Maptiks.js
> +          var maptiksId = maptiksSet ? app.data.getWebAppData().getMaptiks().maptiksId : "demo";
I don't want to see these in the code that all our templates will use. Can this belong on the demo.html page?

2017-07-04 21:10 UTC, phloem7 commented on src/app/storymaps/tpl/core/Maptiks.js
> +          var maptiksId = maptiksSet ? app.data.getWebAppData().getMaptiks().maptiksId : "demo";
I don't think I can send that out from demo.html. I could work that into the "story-loaded-map" topic (or a custom topic), if that's preferred. Is the idea to have a single generic Maptiks.js that will be accessed by all templates?

2017-07-04 21:14 UTC, phloem7 commented on src/app/main-config.js
> +            ['maptiks', '//cdn-dev.maptiks.com/esri3/mapWrapper.js']
done

2017-08-22 19:34 UTC, aspcanada approved these changes

2017-08-22 19:34 UTC, merged